enum {
	FATAL_INTERNAL,
	// assembler
	ERR_UNDEF_LABEL,
	ERR_MULTI_LABEL,
	ERR_DATA_OFS,
	ERR_UNKNOWN,
	ERR_CANTIMM,
	ERR_NO_RET_LAEBEL,
	ERR_OFFSET,
	ERR_DATA_OVER,
	// file
	FATAL_OPEN,
	FATAL_WRITE,
	FATAL_PREPRO,
	ERR_COMMENT,
	ERR_NEEDS_VALUE,
	ERR_NEEDS_CH,
	ERR_ESC,
	// expr
	ERR_CONST_EXPR,
	ERR_TYPE,
	ERR_NEEDS_OP,
	ERR_MULTI,
	ERR_UNBALANCE,
	ERR_EXTRA_WORD,
	// node
	ERR_UNDEF,
	ERR_NOT_POINTER,
	ERR_POINTER_ARITH,
	ERR_ADDRESS,
	ERR_NO_FUNC,
	ERR_NOT_STRUCT,
	ERR_CANT_STRUCT,
	ERR_NO_MEMBER,
	ERR_COMPLEX,
	ERR_SUBST,
	ERR_ARG,
	ERR_ARG_TYPE,
	ERR_CANT_FLOAT,
	ERR_CANT_CONST,
	// context
	ERR_BREAK,
	ERR_CONTINUE,
	ERR_NEEDS_WHILE,
	ERR_KEYWORD,
	ERR_VAR_SIZE,
	ERR_TYPEDEF_UNDEF,
	ERR_TYPEDEF_MULTI,
	// link
	ERR_LINK_UNDEF,
	ERR_LINK_MULTI,
	// prepro
	ERR_UNTERMINATED_IF,
	ERR_INCLUDE,
	ERR_PREPRO,
	ERR_MACRO_ARG,
	ERR_NONE
};

struct ErrorException {};
struct FatalException {};

void ErrorInit();
void Error(int x, ...);
void Fatal(int x, ...);
int ErrorCount();
